выполнение задачи
itedu-tool/exam_ticket_generator pull request #4
Opened 2022-10-20 08:00 UTC by Bozhenashalginskaia

2022-10-20 08:00 UTC, anst-foto commented
![](https://github.trello.services/images/mini-trello-icon.png) [Вёрстка формы входа](https://trello.com/c/qvedoHAp/8-%D0%B2%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B0-%D1%84%D0%BE%D1%80%D0%BC%D1%8B-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0)

2022-10-20 08:05 UTC, anst-foto requested changes
Выделить из html те участки кода, которые относятся непосредственно к задаче.

2022-10-20 08:05 UTC, anst-foto commented on front/public/Author_Teacher.html
> +							<p><input  class="form__active" placeholder="ФИО" type="text" id="name"></p>
```suggestion
							<input  class="form__active" placeholder="ФИО" type="text" name="name" id="name">
```

2022-10-20 12:53 UTC, Bozhenashalginskaia commented
![](https://github.trello.services/images/mini-trello-icon.png) [Вёрстка формы входа](https://trello.com/c/qvedoHAp/8-%D0%B2%D1%91%D1%80%D1%81%D1%82%D0%BA%D0%B0-%D1%84%D0%BE%D1%80%D0%BC%D1%8B-%D0%B2%D1%85%D0%BE%D0%B4%D0%B0)

2022-12-07 07:49 UTC, anst-foto approved these changes

2022-12-07 08:16 UTC, merged